### ISSUE TITLE
Fatal Error: seopress_get_toggle_option

### ISSUE THREAD

**Issue by oppenheimer-** [wp-seopress/wp-seopress-public#12]
I installed the latest update 3.8.0.3 and PRO throws an error:

Fatal error: Uncaught Error: Call to undefined function seopress_get_toggle_option() in /app/public/wp-content/plugins/wp-seopress-pro/seopress-pro.php on line 454

**Comment by wp-seopress** [comment]
Is SEOPress PRO also up to date? the latest version is 3.8 for the PRO.

**Comment by oppenheimer-** [comment]
yes, it has the stable tag 3.8

**Comment by wp-seopress** [comment]
Can you open a ticket from your customer area with an admin access please? 

Thanks

**Comment by oppenheimer-** [comment]
Done. Although the 0error does not occur anymore after re-activating both plugins.
Thank you anyway!

**Comment by wp-seopress** [comment]
This error happens if you have enabled the PRO without the FREE.
Will update our code to avoid the fatal error but the PRO is not supposed to work without the FREE activated.

**Comment by oppenheimer-** [comment]
Perfectly makes sense. Maybe the PRO can be deactived when FREE is being updated. Just an idea.

Merci!
