### ISSUE TITLE
Warning:  array_count_values(): Can only count STRING and INTEGER values!

### ISSUE THREAD

**Issue by Daniel-Richard** [wp-seopress/wp-seopress-public#14]
I've just caught this in the error logs. It was for a WooCommerce product.
Hope the information below would be of some help. :)

--

Warning:  array_count_values(): Can only count STRING and INTEGER values! in /home/.../public_html/wp-content/plugins/wp-seopress/inc/admin/admin-metaboxes-content-analysis-form.php on line 166

Stack Trace
-----------
1. array_count_values(Array(3))
   /home/.../public_html/wp-content/plugins/wp-seopress/inc/admin/admin-metaboxes-content-analysis-form.php:166
2. require_once('/home/...')
   /home/.../public_html/wp-content/plugins/wp-seopress/inc/admin/admin-metaboxes.php:486
3. seopress_content_analysis(WP_Post, Array(4))
   /home/.../public_html/wp-admin/includes/template.php:1343
4. do_meta_boxes(WP_Screen, 'normal', WP_Post)
   /home/.../public_html/wp-admin/edit-form-advanced.php:677
5. include('/home/...')
   /home/.../public_html/wp-admin/post.php:198

**Comment by wp-seopress** [comment]
Hi,

can you share the URL please?

Thanks

**Comment by Daniel-Richard** [comment]
It's on a live website, https://frozenmeat.sg/

**Comment by wp-seopress** [comment]
Will be fixed in the next update
