### ISSUE TITLE
Add capability like manage_options but for SEOpress only.

### ISSUE THREAD

**Issue by SimonvanWijhe** [wp-seopress/wp-seopress-public#15]
I would like to grant my editor role with the capability of 'manage_options' but for SEOpress only.
Now, if I was to give the editor te capability to 'manage_options' it get's full acces for way to many admin settings.

Yoast has the option to add a capability of "wpseo_manage_options". This allows full acces to all Yoast option, but nothing more.

Could this feature be implemented for SEOpress? 

I recently switched from Yoast to SeoPress and there is a lot to like! But this makes me want to go back..

**Comment by wp-seopress** [comment]
Good news, the next update (ETA: tomorrow or next week) will have this feature.

**Comment by SimonvanWijhe** [comment]
Very good news! Thanks.

**Comment by wp-seopress** [comment]
https://www.seopress.org/support/hooks/filter-user-capacities/
