### ISSUE TITLE
Post edit screen crashes due to seopress-counters.min.js

### ISSUE THREAD

**Issue by pedroaraujo74** [wp-seopress/wp-seopress-public#17]
![image](https://user-images.githubusercontent.com/11661857/81730649-c1ba6180-9485-11ea-921f-4173ff90e790.png)

Only seems to be happening in one post for no apparent reason

**Comment by pedroaraujo74** [comment]
Managed to find a workaround. The issue was being caused by a "@" character in the posts's featured image URL/Title.

**Comment by wp-seopress** [comment]
Hi,

this is a known issue, the patch is ready and will be pushed in the next update of our plugin.
