### ISSUE TITLE
CSS Background Color in seopress.min.css conflicts with other WP plugin

### ISSUE THREAD

**Issue by treefairy** [wp-seopress/wp-seopress-public#2]
A site I'm working on has SEOpress and "Ultimate Addons for Visual Composer" (UAVC) installed. (both plugins are the most recent versions). 

The .container style in seopress.min.css is being applied to UAVC's settings screen which also uses the .container class. I've included a picture below so you can see what I mean:

![uavc-with-seopress](https://user-images.githubusercontent.com/10353506/34799217-20eacece-f6b3-11e7-804c-2bda095a70a8.jpg)

Is it possible to make the .container rule in seopress.min.css more specific so it doesn't get applied to other plugins? Nothing functionality wise in this other plugin has been affected.

Cheers.

**Comment by wp-seopress** [comment]
Solved a long time ago
