### ISSUE TITLE
Slow request for Default Facebook Image

### ISSUE THREAD

**Issue by pesamo73** [wp-seopress/wp-seopress-public#20]
Hello, I have discovered that the request (SELECT post_id, meta_value FROM postmeta WHERE meta_key = '_wp_attached_file' AND meta_value = '2020/05/app-icon.png') of default FaceBook image is very slow (3sec) as Ι have about 9 millions rows in postmeta. I propose to save the post_id and recall the attachment by the post_id.

Thank you in advance

**Comment by wp-seopress** [comment]
Hello, we used attachment_url_to_postid (https://developer.wordpress.org/reference/functions/attachment_url_to_postid/) to handle this (inc/functions/options-social.php).

Yes this function is not very efficient. We will see what it is possible to do.

**Comment by pesamo73** [comment]
Hello, I have solved my problem with a few lines of code in the function seopress_social_fb_img_size_from_url($url).
This function call one or two times 'attachment_url_to_postid' to get the width, height, and alt. So I get directly the width and height from the $url, but I sacrificed the 'og:image:alt' which is not very important for me. The performance now is the same as when I disable the seopress plugin.

**Comment by wp-seopress** [comment]
@pesamo73 after digging into this, unfortunately, this is not possible to optimize this function.
WP stores absolute URLs instead of ID, so the only way to get width, height and alt is to use the native WP function attachment_url_to_postid.
