### ISSUE TITLE
jQuery referenceError for eCommerce tracking

### ISSUE THREAD

**Issue by Buzut** [wp-seopress/wp-seopress-public#21]
It's written in the version 3.8.6 changelog that "Remove Jquery dependency from Google Analytics tracking".

Yet I have jQuery errors and, as a matter of fact, there are many references to it in [options-google-analytics.php](https://github.com/wp-seopress/wp-seopress-public/blob/master/inc/functions/options-google-analytics.php) and [options-google-ecommerce.php](https://github.com/wp-seopress/wp-seopress-public/blob/master/inc/functions/options-google-ecommerce.php).

When can we finally say goodbye to this old burden?

**Comment by wp-seopress** [comment]
Hi,

we'll take care of this for version 4.3 or 4.4 to completely remove jQuery.
ETA: January/February 2021.
