### ISSUE TITLE
Full-size original image for post thumbnail in image sitemap

### ISSUE THREAD

**Issue by cookingwithdog** [wp-seopress/wp-seopress-public#30]
Hello,

I noticed my image sitemap uses 825x510px post thumbnail images instead of the full-size original images. Please consider using full-size images for the sitemap.

/templates/sitemap/single.php

I modified the line 161 to use full-size images in the image sitemap.

[New]
`$post_thumbnail    = get_the_post_thumbnail_url($post, 'full');`

[Instead of]
`$post_thumbnail    = get_the_post_thumbnail_url($post);`

Thank you for creating this plugin!

![image-sitemap-get_the_post_thumbnail_url](https://user-images.githubusercontent.com/84653339/119965995-d2347000-bfe5-11eb-8240-cdb4f6fb1b3f.jpg)

**Comment by wp-seopress** [comment]
Hi @cookingwithdog 

thank you for your suggestion.

This issue will be solved in version 5.

ETA: end of June.
