### ISSUE TITLE
How can i add custom meta tags and titles and social programtically in woocommerce products

### ISSUE THREAD

**Issue by pratikraman-dev** [wp-seopress/wp-seopress-public#33]
i need to change this fields of each products programtically when my webhook arrives in my custom plugin 

can anyone help me out!! 

![image](https://user-images.githubusercontent.com/8825570/128984545-9fb31a63-46e1-4e5f-972e-38f71909c034.png)

**Comment by wp-seopress** [comment]
Hi,

this guide will help you: https://www.seopress.org/support/guides/list-of-all-post-metas-generated-by-seopress/

Please open a support ticket from your customer area if you need help.
