### ISSUE TITLE
PHP Error : wp-content/plugins/wp-seopress/inc/admin/blocks/notifications-center.php:1049

### ISSUE THREAD

**Issue by wrivkap** [wp-seopress/wp-seopress-public#49]
GETTING THIS ERROR WITH QUERY MONITOR PLUGIN:
I only need seopress for the schema structure not the meta title and tag features. I have deactivated all except the aforementioned. The SEOPress plugin seems to use alot of memory from the site and slows it down at times even though I only need schema structure.

ERROR:
wp-content/plugins/wp-seopress/inc/admin/blocks/notifications-center.php:1049 

<img width="2046" alt="Screen Shot 2022-04-21 at 2 36 57 PM" src="https://user-images.githubusercontent.com/101981793/164530625-b80cb5dd-6078-4ac2-903d-2f63248b70d8.png">

<img width="275" alt="Screen Shot 2022-04-21 at 2 38 47 PM" src="https://user-images.githubusercontent.com/101981793/164530813-07fdcd99-bd90-4b49-8964-5cfd9745b7a3.png">

**Comment by wp-seopress** [comment]
Hi, please open a support ticket from your customer area on seopress.org to help you debug this. Thank you for understanding.
