### ISSUE TITLE
Motomo Form Input Fields Auto Populate

### ISSUE THREAD

**Issue by VR51** [wp-seopress/wp-seopress-public#53]
The Motomo form in SEOPress > Analytics > Motomo needs the Authentication field and the Cross Domain field to be set to not be auto populated by web browser autofill.

Each time I save the page when setting up a site I have to clear those two fields before clicking save when all I want to do is disable the dashboard widget.

Thanks

**Comment by wp-seopress** [comment]
Unfortunately, this is not possible, see this SO thread:

https://stackoverflow.com/questions/15738259/disabling-chrome-autofill

:(
