### ISSUE TITLE
Error 500 Bugs

### ISSUE THREAD

**Issue by agusgrana** [wp-seopress/wp-seopress-public#57]
Hello. 
I have an Oxygen Builder 4.0, PHP 8.0 project, Seopress pro 6.4. I have noticed that the page parsing is not working, it returns a 500 error and as far as I have been able to debug it is a PHP error. 

03:14:00.329 XHRGEThttps://xxxxx.es/wp-admin/admin-ajax.php?action=seopress_do_real_preview&post_id=1569&tax_name=&origin=post&post_type=product&seopress_analysis_target_kw=Nuxe Huile Prodigieuse Or 100 ml&_ajax_nonce=6a957575e957
[HTTP/2 500 Internal Server Error 4283ms] 03:14:00:329

I've tried to fix it, but this problem not server problem, but how it sends data with PHP >= 8.0. 
Thanks for all

**Comment by wp-seopress** [comment]
Hi,
please open a support ticket from your customer area on seopress.org.
Thank you for understanding.
