### ISSUE TITLE
Deprecated notices with PHP 8.1 

### ISSUE THREAD

**Issue by RobOT05442309** [wp-seopress/wp-seopress-public#60]
Hello,

When activating the plugin after installation (I think it will also work if no configuration as been done) on a fresh WordPress install, with debug log enable to report any errors, I found two deprecated notices.

### First notice:

```
Deprecated: parse_url(): Passing null to parameter #1 ($url) of type string is deprecated in /<path-to-wordpress>/wp-includes/media.php on line 5116
```

This notice call stack link to those SEOPress informations:

```
- seopress_social_fb_img_hook( '' ) > class-wp-hook.php:308
- seopress_social_fb_img_size_from_url( $url = NULL, $post_id = ??? ) > options-social.php:715
- attachment_url_to_postid( $url = NULL )	> options-social.php:630
- parse_url( $url = NULL ) > media.php:5116
```

### Second notice:

```
Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /<path-to-wordpress>/wp-includes/media.php on line 5123
```

```
seopress_social_fb_img_hook( '' ) > class-wp-hook.php:308
seopress_social_fb_img_size_from_url( $url = NULL, $post_id = ??? ) > options-social.php:715
attachment_url_to_postid( $url = NULL )	> options-social.php:630
strpos( $haystack = NULL, $needle = 'http://localhost/wp-content/uploads/' ) > media.php:5123
```

### Workaround:

Theses notices disappear if I disable all the "Social" options using toggle in SEOPress settings.

### Request:

This is NOT a fatal error, so there is no rush to patch or anything, but I report this here to let you know I encounter this issue while working on a custom theme with PHP error report set to report everything. I haven't test this with PHP 8.2 but maybe the deprecation could be more blocking than a simple notice (I haven't check the doc about this).

Anyway, thanks for your plugin and work! Have a nice day.

**Comment by wp-seopress** [comment]
Hi,

thank you for your feedback!

This is a known issue that we already that in our todo list.

ETA: 6.6 or 6.7.
