### ISSUE TITLE
Warning: Attempt to read property "ID" on null

### ISSUE THREAD

**Issue by fvanzeijl** [wp-seopress/wp-seopress-public#62]
Hi,

there are some bots who request the blog-index page with parameter `?author=AUTHOR_ID`.
So our error-tracking-system noticed us with following error:

```php
Warning: Attempt to read property "ID" on null in plugins/wp-seopress/inc/functions/options-titles-metas.php on line 156
```

The method tries to get the ID from a post-object (`$post->ID`). But on blog-index-page there is no post-object.

**Comment by wp-seopress** [comment]
Hi,

added to our private Github account fix this case.

No ETA yet.

Thanks
