### ISSUE TITLE
FAQ JSON LD converter enhancement 

### ISSUE THREAD

**Issue by oppenheimer-** [wp-seopress/wp-seopress-public#63]
A nice feature for the FAQ block could be the ability to alternatively use existing JSON LD as input in a plain text area.

There could be a mode switcher to allow for the regular behaviour as of today and the new text area. The benefit would be to quickly style existing data for the frontend without manual labour involved.

**Comment by wp-seopress** [comment]
Hi,

I'm not sure to understand what you want. Currently, you can use the Schema metabox, manual tab, and use either the FAQ type, or the custom one to paste your JSON. Might be the solution.

**Comment by oppenheimer-** [comment]
Let me re-phrase it a bit clearer:

It's not about solely getting the JSON LD on the page, but enhancing the **FAQ block** to work 2 fold. 

1) The classic, but cumbersome way as it works today
2) An alternative mode to accept a pre-existing JSON+LD string to be parsed in the background and used instead of the manually written QAs to generate a formatted view.

![image](https://github.com/wp-seopress/wp-seopress-public/assets/10992675/6340e862-9fa4-4d4d-aa1e-b6476e430d56)

**Comment by wp-seopress** [comment]
OK I understand but why not use the Custom schema type with the exact same textarea from our Google Structured data types metabox?

**Comment by wp-seopress** [comment]
No it will only output JSON schema but you can use it in conjunction with our Google Structured data types metabox. We would like to avoid confusion for end users but adding such a field.

**Comment by oppenheimer-** [comment]
Ah well, if you presume it will confuse end users, which i am happily, then there can't be done anything about it. I'm not entirely sure my idea to enhance your great additions to the FAQ block was understood though.
